/**
 * @file Parser.hpp
 * @brief This file contains the definition of the Parser class.
 * 
 * The Parser is responsible for converting a list of tokens generated by the lexer
 * into an abstract syntax tree (AST).
 */

#pragma once

#include <string>
#include <string_view>
#include <vector>
#include <optional>

#include "vee/core/CoreDefines.hpp"
#include "vee/core/CoreTypedefs.hpp"
#include "vee/core/InternalErrorHandling.hpp"
#include "veec/CoreDefines.hpp"
#include "veec/compilation/CompilationContext.hpp"
#include "veec/basic/Token.hpp"
#include "veec/basic/TokenList.hpp"
#include "veec/basic/StringId.hpp"
#include "veec/source/Identifier.hpp"
#include "veec/source/SourceManager.hpp"
#include "veec/source/SourceRange.hpp"
#include "veec/ast/AstContext.hpp"
#include "veec/ast/AstNode.hpp"
#include "veec/ast/AstFwd.hpp"
#include "veec/ast/CompilationUnitNode.hpp"

VEEC_NAMESPACE_BEGIN
namespace parsing {

using Token = basic::Token;
using TokenType = basic::TokenType;

/**
 * @brief Responsible for producing an AST from a list of tokens.
 */
class Parser {
public:
    /**
     * @brief Creates a parser with the given context.
     * @param ctx The compilation context object.
     */
    Parser(compilation::CompilationContext& ctx, const basic::TokenList& tokenList)
        : _ctx(ctx), _ast(ctx.ast), _tokenList(tokenList) {}

    ~Parser() = default;

    /**
     * @brief Parses the tokens and produces an AST.
     * @return A pointer to the root of the AST (CompilationUnitNode),
     * or nullptr if parsing failed/no tokens were provided.
     */
    ast::CompilationUnitNode* parse();

private:
    struct BindingPower {
        u8 left;
        u8 right;

        BindingPower(u8 left, u8 right)
            : left(left), right(right) {}
    };

    compilation::CompilationContext& _ctx;
    ast::AstContext& _ast;
    int _currentTokenIndex = 0;
    const basic::TokenList& _tokenList;

    //
    // Parse methods
    //

    // Top-level parsers
    ast::CompilationUnitNode* parseCompilationUnit();
    ast::ItemNode* parseItem();
    ast::ItemNode* parseMemberItem();

    // Names
    ast::QualifiedNameNode* parseQualifiedName();
    
    // Generics
    ast::GenericArgsNode* parseGenericArgs();

    // Declarations
    ast::DeclarationNode* parseDeclaration();
    ast::DeclarationNode* parseMemberDeclaration();
    ast::ModuleDeclNode* parseModuleDeclaration();
    ast::FunctionDeclNode* parseFunctionDeclaration();
    ast::ParameterDeclNode* parseParameterDeclaration();
    ast::ClassDeclNode* parseClassDeclaration();
    ast::MethodDeclNode* parseMethodDeclaration();
    ast::FieldDeclNode* parseFieldDeclaration();
    ast::VariableDeclNode* parseVariableDeclaration();

    // Statements
    ast::StatementNode* parseStatement();
    ast::StatementNode* parseMemberStatement();
    ast::BlockStmtNode* parseBlockStatement();
	ast::ExpressionStmtNode* parseExpressionStatement();
    ast::IfStmtNode* parseIfStatement();
    ast::LoopStmtNode* parseLoopStatement();
    ast::WhileStmtNode* parseWhileStatement();
    ast::ForStmtNode* parseForStatement();
    ast::ReturnStmtNode* parseReturnStatement();
    ast::UseStmtNode* parseUseStatement();

    // Expressions (Pratt engine)
    ast::ExpressionNode* parseExpression();
    ast::ExpressionNode* parseExpressionBP(i32 minBP);
    ast::ExpressionNode* parsePrefixExpression();
    ast::ExpressionNode* parseInfixExpression(ast::ExpressionNode* lhs);
    ast::NameExprNode* parseNameExpression();
    ast::ExpressionNode* parseIdentifierLikeExpression();
    ast::ExpressionNode* parseConstructExpression(ast::TypeNode* type = nullptr);
    ast::IntLiteralExprNode* parseIntLiteralExpression();
    ast::FloatLiteralExprNode* parseFloatLiteralExpression();
    ast::StringLiteralExprNode* parseStringLiteralExpression();
    ast::BoolLiteralExprNode* parseBoolLiteralExpression();
    ast::ExpressionNode* parsePrefixUnaryExpression();
    ast::ExpressionNode* parsePostfixUnaryExpression(ast::ExpressionNode* lhs);
    ast::ExpressionNode* parseBinaryExpression(ast::ExpressionNode* lhs);
    ast::ExpressionNode* parseAssignmentExpression(ast::ExpressionNode* lhs);
    ast::ExpressionNode* parseCallExpression(ast::ExpressionNode* callee);
    ast::ExpressionNode* parseIndexExpression(ast::ExpressionNode* object);
    ast::MemberAccessExprNode* parseMemberAccessExpression(ast::ExpressionNode* object);
    ast::ParenthesizedExprNode* parseParenthesizedExpression();

    // Types
    ast::TypeNode* parseType();

    //
    // Helper parsers
    //

    //
    // Parsing helpers
    //

    inline source::Identifier tokenToIdentifier(const Token& token) const {
        VEE_ASSERT(token.type() == TokenType::Identifier, "Token is not an identifier");
        basic::StringId id = _ctx.strings.intern(tokenText(token));
        return source::Identifier{id, token.range()};
    }
    /**
     * @brief Gets the text of a token from the source file.
     * @param token The token to get the text for.
     * @return A string_view of the text corresponding to the token.
     */
    inline std::string_view tokenText(const Token& token) const {
        return token.range().getText();
    }
    /**
     * @brief Combines the ranges of two tokens into a single range.
     * @param begin The first token.
     * @param end The last token.
     * @return A SourceRange that spans from the start of the first token to the end of the last token.
     */
    inline source::SourceRange tokenRange(const Token& begin, const Token& end) const {
        VEE_ASSERT(begin.range().getFile() == end.range().getFile(),
            "Tokens must be from the same source file to combine ranges");

        return source::SourceRange(
            begin.range().getFile(),
            begin.range().getBegin(),
            end.range().getEnd()
        );
    }
    /**
     * @brief Combines the ranges of two SourceRanges into a single range.
     * @param begin The first SourceRange.
     * @param end The last SourceRange.
     * @return A SourceRange that spans from the start of the first range to the end of the last range.
     */
    inline source::SourceRange combineRanges(const source::SourceRange& begin, const source::SourceRange& end) const {
        VEE_ASSERT(begin.getFile() == end.getFile(),
            "SourceRanges must be from the same source file to combine ranges");
        
        return source::SourceRange(
            begin.getFile(),
            begin.getBegin(),
            end.getEnd()
        );
    }

    //
    // Enum converters
    //
    
    ast::UnaryOp tokenTypeToUnaryOp(TokenType type) const;
    ast::BinaryOp tokenTypeToBinaryOp(TokenType type) const;
    ast::AssignmentOp tokenTypeToAssignmentOp(TokenType type) const;
    ast::MemberAccessOp tokenTypeToMemberAccessOp(TokenType type) const;
    ast::BuiltinTypeKind tokenTypeToBuiltinType(TokenType type) const;

    //
    // Pratt engine helpers
    //

    std::optional<u8> getPrefixBindingPower(TokenType type) const;
    std::optional<BindingPower> getInfixBindingPower(TokenType type) const;

    //
    // Parser state helpers
    //

    /**
     * @brief Peeks at the current token without advancing the parser
     * @return The current token.
     */
    const Token& peek() const {
		const_cast<Parser*>(this)->skipTrivia();
        return _tokenList.tokens[_currentTokenIndex];
    }
    /**
     * @brief Checks if the current token matches the expected type.
     * @param expectedType The expected token type to match.
     * @return True if the current token matches the expected type, false otherwise
     */
    inline bool check(TokenType expectedType) const {
        return peek().type() == expectedType;
    }
    /**
     * @brief Checks if the current token matches any of the expected types.
     * @tparam TokenTypes The expected token types to match.
     * @param expectedTypes The expected token types to match.
     * @return True if the current token matches any of the expected types, false otherwise.
     */
    template<typename... TokenTypes>
    inline bool checkAny(TokenTypes... expectedTypes) const {
        return ((check(expectedTypes)) || ...);
    }
    /**
     * @brief Gets the previous token.
     * @return The previous token.
     */
    const Token& previous() const {
        VEE_ASSERT(_currentTokenIndex > 0, "Cannot get previous token when at the beginning of the token list");
        return _tokenList.tokens[_currentTokenIndex - 1];
    }
    /**
     * @brief Advances to the next token and returns the current token.
     * @return The current token before advancing.
     */
    inline const Token& advance() {
        const Token& token = peek();
        if (!isAtEnd())
            _currentTokenIndex++;
        return token;
    }
    /**
     * @brief Checks if the current token matches the expected type and advances if it does.
     * @param expectedType The expected token type to match.
     * @return True if the current token matches the expected type, false otherwise.
     */
    inline bool match(TokenType expectedType) {
        skipTrivia();
        if (check(expectedType)) {
            advance();
            return true;
        }
        return false;
    }
    template<typename... TokenTypes>
    inline bool matchAny(TokenTypes... expectedTypes) {
        if (checkAny(expectedTypes...)) {
            advance();
            return true;
        }
        return false;
    }
    /**
     * @brief Expects the current token to be of a specific type.
     * If it is, advances the parser and returns the token.
     * If not, reports a diagnostic and returns nullptr.
     * @tparam ArgCount The number of arguments to pass to the diagnostic.
     * @param expectedType The expected token type.
     * @param diagDesc The diagnostic descriptor to use if the token does not match.
     * @param args The arguments to pass to the diagnostic.
     * @return A pointer to the expected token if it matches, or nullptr if it does not.
     */
    template<size_t ArgCount, typename... Args>
    inline const Token* expect(TokenType expectedType, const diagnostics::DiagnosticDescriptor<ArgCount>& diagDesc, Args&&... args) {
        if (match(expectedType)) {
            return &previous();
        }
        
        _ctx.diagnostics.report(diagDesc, peek().range(), std::forward<Args>(args)...);
        synchronize();
        return nullptr;
    }
    /**
     * @brief Advances to the end of the current statement/declaration/expression.
     * Call this when an error is hit to prevent cascading and allow recovery.
     */
    inline void synchronize() {
        while (!isAtEnd()) {
            const Token& tk = peek();

            if (tk.type() == TokenType::SemiColon) {
                advance();
                return;
            }
            else if (tk.isKeyword()) {
                return;
            }

            advance();
        }
    }
    /**
     * @brief Skips over any consecutive trivia tokens (whitespace, newlines, etc).
     */
    inline void skipTrivia() {
        while (_currentTokenIndex < static_cast<int>(_tokenList.tokens.size()) 
               && _tokenList.tokens[_currentTokenIndex].type() != TokenType::EndOfFile
               && _tokenList.tokens[_currentTokenIndex].isTrivia()) {
            _currentTokenIndex++;
        }
    }
    /**
     * @brief Checks if the parser has reached an EndOfFile token.
     * @return True if the parser has reached an EndOfFile token, false otherwise.
     */
    inline bool isAtEnd() const {
        return check(TokenType::EndOfFile);
    }
};

} // namespace parsing
VEEC_NAMESPACE_END
